# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - id: get-repo-values
              run: |
                  url=https://$(echo "${{github.repository}}" | sed "s/\//.github.io\//")
                  echo "url=$url" >> $GITHUB_OUTPUT
            - name: Update package.json homepage
              uses: jossef/action-set-json-field@v1
              with:
                  file: package.json
                  field: homepage
                  value: ${{ steps.get-repo-values.outputs.url }}
            - run: npm ci
            - run: npm run lint
            - run: npm run test -- --coverage |& tee ./public/test_report.txt
            - run: echo "<html><head><meta http-equiv='refresh' content='0; URL=${{github.server_url}}/${{github.repository}}' /></head><body>Redirecting to repository</body></html>" > ./public/github.html
            - run: npm run build --if-present

            - name: Deploy
              run: |
                  git config --global user.name ${user_name}
                  git config --global user.email ${user_email}
                  git remote set-url origin https://${github_token}@github.com/${repository}
                  npm run deploy
              env:
                  user_name: "github-actions[bot]"
                  user_email: "github-actions[bot]@users.noreply.github.com"
                  github_token: ${{ secrets.GH_TOKEN }}
                  repository: ${{ github.repository }}
